---
name: lint
on: push
defaults:
  run:
    shell: bash
jobs:
  lint:
    runs-on: ['hyperenv', 'medium']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: cfn-lint
      run: |
        pip install cfn-lint==0.72.1
        cfn-lint -i W3002 -t mastodon.yaml